Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Code Analysis
+name: Python Syntax Check
 
 on:
   push:
@@ -7,28 +7,23 @@ on:
     branches: [ "main" ]
 
 jobs:
-  analyze:
+  syntax_check:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: ["3.8", "3.9", "3.10"]  # Замените на ваши версии Python
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up Python ${{ matrix.python-version }}
+      - name: Set up Python 3.10
         uses: actions/setup-python@v4
         with:
-          python-version: ${{ matrix.python-version }}
+          python-version: 3.10
 
-      - name: Install dependencies
+      - name: Check Python syntax
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt # Замените на ваш файл зависимостей
-
-      - name: Run linters and code analyzers
-        run: |
-          pip install flake8 pylint   # Замените на нужные вам линтеры
-          flake8 . 
-          pylint **/*.py 
+          python -m compileall .
+          if [ $? -ne 0 ]; then
+             echo "Syntax errors found!"
+             exit 1
+          else
+             echo "No syntax errors found."
+          fi
